### PR TITLE
Setting a default value for `TableNamePrefix`

### LINKED ISSUE #7: Providing a Connection String only results in an exception
There is a method that allows you to register with just a connection string:

```csharp
    public static IKernelMemoryBuilder WithPostgres(this IKernelMemoryBuilder builder, string connString)
    {
        builder.Services.AddPostgresAsMemoryDb(connString);
        return builder;
    }
```

But this will cause the `PostgresConfig` type that is created to fail the validation because the `TableNamePrefix` field is an empty string.

### PR DESCRIPTION
**Pull request by aaronpowell**
Fixes #7

Setting a default value for `TableNamePrefix` so if you only provide a connection string it won't fail validation

### CODE REVIEW

**Review by dluc — APPROVED** [review]

File: PostgresMemoryStorage/PostgresConfig.cs [hunk 1]
```diff
@@ -1,4 +1,4 @@
-// Copyright (c) Microsoft. All rights reserved.
+﻿// Copyright (c) Microsoft. All rights reserved.
```
Comment (dluc) [inline PostgresMemoryStorage/PostgresConfig.cs:1]:
```suggestion
﻿// Copyright (c) Microsoft. All rights reserved.
```

**Review by dluc — COMMENTED** [review]
something about the BOM symbol here I think
